trigger:
  branches:
    include:
      - master
      - feature/*
  paths:
    include:
      - 'Company/*'

pool:
  demands: JAVA_HOME_11_X64

steps:
- task: Gradle@2
  displayName: 'gradlew clean build'
  inputs:
    gradleWrapperFile: 'Company/gradlew'
    workingDirectory: Company
    tasks: 'clean build'
