trigger:
  branches:
    include:
      - master
      - feature/*
  paths:
    include:
      - 'Company/*'

pool:
  demands: java

steps:

- task: Gradle@2
  displayName: 'gradlew clean build'
  inputs:
    gradleWrapperFile: 'Company/gradlew'
    workingDirectory: Company
    tasks: 'clean build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    codeCoverageToolOption: 'JaCoCo'
    codeCoverageClassFilesDirectories: 'Company/build/classes/java/main'
    sonarQubeRunAnalysis: false

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/Company/build/reports/jacoco/test/jacocoTestReport.xml'